ClickHouse/clickhouse-odbc

README.md
when building on older unixodbc, the following error appear
```
clickhouse-odbc/driver/environment.h:49:24: error: ‘SQL_OV_ODBC3_80’ was not declared in this scope
int odbc_version = SQL_OV_ODBC3_80;
```
I yet haven't found an elegant way how to check odbc version in CMake, let us just document it in README
=> specify required unixodbc version

CMakeLists.txt, cmake/Modules/CheckODBCversion.cmake
at least ubuntu trusty is shipped with older unixodbc. so, we should check not only for presense of unixodbc, but also for certain version
=> cmake check for unixodbc version

vs/installer32/Product.wxs, vs/installer64/Product.wxs
it seems AppVeyor is not enabled anymore for this repo.
without "bundled" CRT an installation fails on "clean" computer (which does not have Visual Studio installed)
=> bundle visual c++ redistributable into installer

README.md
After having this [issue](https://github.com/yandex/clickhouse-odbc/issues/26) discussed, looks like it would be useful to describe how to clone project correctly, so others would not ask such questions in future
=> Add submodules description into installation manual

cmake/find_ssl.cmake
This helps with the use of a non-standard OpenSSL location.
=> Only set OPENSSL_ROOT_DIR if not defined

docker/Dockerfile, docker/Dockerfile.centos7, driver/ut/nano.cpp
Added docker build scripts to build & test clickhouse-odbc in ubuntu & centos. 
I've also fixed one test, failing due to absence of database.
Currently those tests are failing in that builds:
**ubuntu**:
`3 - clickhouse-odbc-nano-w (Failed)` - some encoding problems. clickhouse get one letter 's' instead of query. Maybe related to NANODBC_ENABLE_UNICODE flag
**centos**:
`2 - clickhouse-odbc-nano (Failed)` & `3 - clickhouse-odbc-nano-w (Failed)` -  both failing to start with exception:
```../contrib/nanodbc/nanodbc/nanodbc.cpp:772: S100: [unixODBC][Driver Manager]Invalid attribute value``` 
https://github.com/nanodbc/nanodbc/blob/107d6c043c8171b72496d55b46932d1ea946ebc0/nanodbc/nanodbc.cpp#L772 
(some API versions mismatch?)
10 - iusql-default (Failed): something strange for some reason …
=> Docker tests

.travis.yml, test/test.sh
Testing driver not only with unit-tests, but also with test scripts from ./test directory
ClickHouse-server is started in docker;
Unfortunately, docker is not supported on MacOSX in Travis, so only running unit-tests
nanoodbc failed to build on Travis, hence not using it too.
=> Testing driver on Travis

cmake/find_ltdl.cmake
Detecting that distro is Debian or Ubuntu-based not by distribution ID (with `lsb_release -is`) but from `/etc/debian_version`, which MUST be present for all Debian-based distros.
=> Fixed build on Debian and Ubuntu-based distros that override distribution ID

driver/format/ODBCDriver2.cpp, driver/format/ODBCDriver2.h, driver/format/RowBinaryWithNamesAndTypes.cpp, driver/format/RowBinaryWithNamesAndTypes.h, driver/result_set.h, driver/test/statement_parameters_it.cpp, driver/utils/type_info.h
Added thin wrappers and conversion routines for type categories used during conservative value conversions: `WireTypeAnyAsString`, `WireTypeDateAsInt`, `WireTypeDateTimeAsInt`.
=> Delay conversions during data fetching from the data source

driver/api/odbc.cpp, driver/format/ODBCDriver2.cpp, driver/format/RowBinaryWithNamesAndTypes.cpp, driver/result_set.cpp
...since they come as strings, they can be stored and served as strings.
Note, that this is not the case for `RowBinaryWithNamesAndTypes` format. When using it, unsupported types will cause hard failures.
=> Treat unknown types as Strings in ODBCDriver2 format

driver/result_set.cpp, driver/result_set.h, driver/utils/type_info.h, driver/utils/unicode_conv.h
Closes https://github.com/ClickHouse/clickhouse-odbc/issues/220 (specific case described there).
Passing (reused persistent) context object with heavy converter instances to Unicode conversion functions.
=> Store and pass stateful converters in conversion contexts

driver/escaping/lexer.cpp, driver/test/escape_sequences_ut.cpp
Closes #258
Closes #281
Review IDENT token parsing, to allow any characters in backtick-wrapped identifiers, and allow mixing backtick-wrapped identifiers and simple ones when used with connecting dot
=> Fix for IDENT token parsing when substituting escape sequences

driver/escaping/escape_sequences.h, driver/test/escape_sequences_ut.cpp
* Updated test case names to be more self-evident
* Added exmplanatory comment to replaceEscapeSequences().
=> Minor modifications

.travis.yml, README.md, driver/statement.cpp, driver/test/statement_parameters_it.cpp, test/deploy_and_run_clickhouse_macos.sh
Closes #236
Closes #294
May help with #298 too
This changes are reflecting the following changes in ClickHouse server parameter parsing behavior: https://github.com/ClickHouse/ClickHouse/issues/7488 and https://github.com/ClickHouse/ClickHouse/pull/8517
=> Switch to ClickHouse version 20.3 as a baseline (changes NULL param string format)

CMakeLists.txt, CPackLists.txt, README.md, cmake/Modules/FindMDAC.cmake, cmake/Modules/FindUnixODBC.cmake, cmake/Modules/FindiODBC.cmake, cmake/arch.cmake, packaging/odbcinst.ini.sample, test/deploy_and_run_clickhouse_macos.sh
=> RPM packaging via CPack

driver/test/misc_it.cpp, driver/utils/type_info.h, test/deploy_and_run_clickhouse_macos.sh
Fixes #315.
May help with #307 (case 1).
https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/odbc/reference/syntax/sqlgetdata-function.md#L72
=> Fix the behavior of SQLGetData for cases when the size of output buffer is 0

driver/connection.cpp, driver/connection.h, driver/statement.cpp, test/test.sh
Generating a random session_id, if none is specified in connection URI in config.
=> Session id per connection

.github/workflows/macOS.yml
It is not properly supported right now and fails to compile in multiple ways.
Checked against clang 11-14
=> Disabled brew clang variant on CI/CD

.github/workflows/Windows.yml
Windows-2016 server hosted runners are no longer available:
https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/
=> Removed windows-2016 from matrix

.github/workflows/Docker.yml, .github/workflows/Linux.yml, .github/workflows/Windows.yml, .github/workflows/debug.yml, .github/workflows/macOS.yml
Uploading Release binaries of Windows and macOS from corresponding workflows.
Linux binaries are uploaded from Docker workflow since it builds\tests binaries on CentOS 7, making those more portable.
=> Uploading release artifacts

.github/workflows/Docker.yml, .github/workflows/Linux.yml, test/docker/Dockerfile
1. Switch ubuntu to 22.04
2. Change docker build from centos to ubuntu as centos due to EOL has many issues with packages installation. (If needed will be resurrected later)
=> CI: Migrate to Ubuntu 22.04

driver/escaping/escape_sequences.cpp, driver/test/escape_sequences_ut.cpp
Fixes https://github.com/ClickHouse/clickhouse-odbc/issues/466:
- Fixes an issue where the call to the locate function always ignores the `start_pos` parameter.
- Fixes an issue where the call to the locate function results in an error when `start_pos` is not specified.
Additionally:
- Ensures that the order of arguments remains unchanged during escape sequence replacement. To achieve this, ClickHouse's `position` function has been replaced with ClickHouse's `locate` function, which has the same argument order as the ODBC `locate` function.
- Also fixes https://github.com/ClickHouse/clickhouse-odbc/issues/462
=> Fix issues with the locate function call

contrib/poco/NetSSL_Win/src/SecureSocketImpl.cpp
When the SecureSocketImpl instance is reused after being closed — either due to a timeout or by SQLFreeStmt(stmt, SQL_CLOSE) — the new handshake might run with a read buffer that has shrunk to the size of the last payload, while still assuming it retains its initial size. This occurs in SecureSocketImpl::performClientHandshakeLoopReceive():
```
int n = receiveRawBytes(
_recvBuffer.begin() + _recvBufferOffset,
IO_BUFFER_SIZE - _recvBufferOffset);
```
Here, the code assumes that the buffer is at least IO_BUFFER_SIZE. However, after the connection is reused, the buffer may be smaller. To fix this, we restore the buffer size to the expected IO_BUFFER_SIZE before performing the handshake. This fix is taken from the latest version of the Poco library.
In the future, we should update the entire …
=> Reset the read buffer of Poco's SecureSocketImpl before the handshake

contrib/poco/Foundation/src/Environment_WIN32.cpp
In function `nodeIdImpl`, the pointer `pAdapterInfo` at line 8 cannot reach any free site before the function returns at line 19. Thus there is a memory leak bug. Here is the original code:
```c++
pAdapterInfo = reinterpret_cast<IP_ADAPTER_INFO*>(new char[len]);         // memory allocated here
// Make an initial call to GetAdaptersInfo to get
// the necessary size into len
DWORD rc = GetAdaptersInfo(pAdapterInfo, &len);
if (rc == ERROR_BUFFER_OVERFLOW) 
{
delete [] reinterpret_cast<char*>(pAdapterInfo);
pAdapterInfo = reinterpret_cast<IP_ADAPTER_INFO*>(new char[len]);
}
else if (rc != ERROR_SUCCESS)
{
return;          // memory leak here
}
``` 
We add a free operation before the return statement.
=> Free pointer `pAdapterInfo` before the function `nodeIdImpl` returns

.github/workflows/Linux.yml, .github/workflows/macOS.yml
Recent versions of CMake have dropped compatibility with versions earlier than 3.5. This change updates the minimum required version to 3.5 to prevent build errors.
=> Bump CMake minimum version to 3.5

.github/workflows/Linux.yml, .github/workflows/Windows.yml, .github/workflows/macOS.yml
Previously, we only ran GitHub Actions for PRs targeting the `master` branch. However, we sometimes have parallel branches, such as the `beta` branch.
=> Enable GitHub Actions for all PRs

.github/workflows/Windows.yml, test/docker-compose.yml
This change enables integration tests, including the Python-based tests, in the Windows CI workflow. The preferred approach was to reuse as much as possible from the existing and functional Linux workflow. However, ClickHouse does not run natively on Windows, nor does Docker, which is used to run ClickHouse in the Linux workflow. To address this, additional steps were added to the workflow: install WSL2 with Ubuntu 24.04, and install Podman as a drop-in replacement for Docker within the WSL2 environment.
Details:
- Updated the GitHub Actions runner image from `windows-2019` to `windows-2025`, which supports WSL2.
- Added steps to enable WSL with `Ubuntu-24.04`, install Podman on it, and run `podman-compose` to start a ClickHouse server, similar to the Linux workflow.
- Modified …
=> Enable unit and integration tests in the Windows pipeline

driver/api/impl/impl.cpp, driver/api/impl/impl.h, driver/api/odbc.cpp, driver/diagnostics.cpp, driver/diagnostics.h, driver/test/misc_it.cpp, test/src/e2e/test_sanity.py
The ODBC standard has a special way to get the version of the DBMS using `SQLGetInfo` with `SQL_DBMV_VER`. This change implements this option.
=> Implement SQLGetInfo(SQL_DBMV_VER) to get the version of the ClickHouse Server

driver/connection.cpp, driver/test/CMakeLists.txt, driver/test/authentication_it.cpp
The driver previously failed when a password contained a tilde (~). 
See: https://clickhouse.com/docs/knowledgebase/ODBC-authentication-failed-error-using-PowerBI-CH-connector
This change removes that limitation and adds tests for passwords with various special characters.
=> Allow tilde (~) in passwords

.github/workflows/Linux.yml, .github/workflows/Windows.yml, test/src/e2e/test_datatypes.py, test/src/util/utils.py
It is generally not recommended to pass values directly in SQL statements when using pyodbc; instead, values should be passed as parameters. However, in our tests, we specifically want to embed values in the SQL statement and then verify the result using a parameterized query.
To avoid unexpected character encoding/decoding issues, all values containing special characters are now base64-encoded in the SQL statements and decoded by ClickHouse.
Additionally, all tables created during testing are now properly deleted.
=> Enable Python E2E tests for the Unicode Driver

driver/api/impl/impl.cpp, driver/api/odbc.cpp, driver/config/config.cpp, driver/config/config.h, driver/platform/platform.h, driver/platform/win/setup.cpp, driver/test/authentication_it.cpp, driver/test/buffer_filling_ut.cpp, driver/test/client_test_base.h, driver/test/client_utils.h, driver/test/column_bindings_it.cpp, driver/test/datetime_it.cpp, driver/test/misc_it.cpp, driver/test/performance_it.cpp, driver/test/result_set_reader.hpp, driver/test/statement_parameter_bindings_it.cpp, driver/test/statement_parameters_it.cpp, driver/test/type_info_it.cpp, driver/utils/conversion.h, driver/utils/conversion_icu.h, driver/utils/resize_without_initialization.h, driver/utils/string_pool.h, driver/utils/type_info.cpp, driver/utils/type_info.h
ODBC API requires strings to be passed as pointers to arrays of unsigned char and unsigned short. This led the design, and especially the tests, to use std::basic_string instantiations that are not allowed by the C++ standard. This prevents updating libc++ to a newer version, because libc++ has removed all non-standard specializations. The only specializations that remain are for char, wchar_t, char8_t, char16_t, and char32_t.
This change removes all uses of non-standard instantiations of std::basic_string, i.e., std::basic_string<SQLCHAR> and std::basic_string<SQLWCHAR>, and replaces them with the standard std::string and std::u16string. For portability, char and char16_t are aliased by PTChar (portable text character), which is a typedef that depends on the type of the build (UNICODE or …
=> Remove use of non-standard std::char_traits
